{% set name = "planetmapper" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/planetmapper-{{ version }}.tar.gz
  sha256: 7abed72635a657f5f4da83e6fe3d86e6adfdaffd69f26bbc6eeae6a5e7f67fa9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - planetmapper = planetmapper.cli:main

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - astropy
    - matplotlib-base
    - numpy
    - pillow
    - spiceypy
    - scipy
    - photutils
    - tqdm
    - pyproj
    - typing-extensions

test:
  imports:
    - planetmapper
  commands:
    - pip check
    - planetmapper --help
    - planetmapper --version
  requires:
    - pip

about:
  home: https://github.com/ortk95/planetmapper
  summary: 'PlanetMapper: A Python package for visualising, navigating and mapping Solar System observations'
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://planetmapper.readthedocs.io/
  dev_url: https://github.com/ortk95/planetmapper

extra:
  recipe-maintainers:
    - ortk95
